import { ThemeProvider } from "@/components/context/ThemeContext"
import Navbar from "@/components/NavBar/navbar"
import { Inter , Montserrat} from "next/font/google"
import "bootstrap/dist/css/bootstrap.css"
import './globals.css'


const inter = Inter({subsets:['latin']})
const lalezar = Montserrat({subsets:['latin'],weight : ['400' , '600' ,'900']})

export const metadata = {
  title: 'Ziad',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  let mode = "dark"

 return (
    <html lang="en">
      <body className={lalezar.className }>
        <ThemeProvider>
          <Navbar />
          {children}  
          </ThemeProvider>
      </body>
    </html>
  )
}
